spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 215MB
  application:
    name: visualizer

security:
  firebase-properties:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-properties:
    domain: ${DOMAIN}
    path: /
    http-only: true
    secure: true
    max-age-in-minutes: 7200
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /session/login
    - /gamePublic/**
  exposed-headers:
    - X-Xsrf-Token